version: '3'

services:
  pgduck:
    image: rubiklabs/pgduck:0.0.9
    ports:
      - "5433:5433"
      - "8282:8282"
      - :5444:5444
    environment:
      - OFFICIAL_DUCKDB_EXTENSIONS=httpfs,aws,azure
      - LOCAL_DUCKDB_EXTENSION_REPO=/repository
      - LOCAL_DUCKDB_EXTENSIONS=iceberg
      - PGDUCK_HOST=0.0.0.0
      - PGDUCK_PORT=5433
##    volumes:
##      - ./data:/data
##      - /Users/devendra/work/dataos/flare/dataout:/dataos