version: '3'

services:
  pgduck:
    image: rubiklabs/flash:0.0.1-dev
    ports:
      - "5433:5433"
      - "8282:8282"
      - "5444:5444"
    environment:
      - OFFICIAL_DUCKDB_EXTENSIONS=httpfs,aws,azure,iceberg
      - PG_HOST=0.0.0.0
      - PG_PORT=5433
      - CONFIG_FILE_PATH="/stack/sample-input.yaml"
      - DATAOS_RUN_AS_APIKEY=*************************
      - DATAOS_SECRET_DIR=/secret
      - DEPOT_SERVICE_URL=*************************
      - LOG_LEVEL=info
      - INIT_SQLS=set azure_transport_option_type = 'curl';SET azure_read_transfer_concurrency = 5;
    volumes:
      - ../stack:/stack