DATAOS_RUN_AS_USER = "DATAOS_RUN_AS_USER"
DATAOS_RUN_AS_APIKEY = "DATAOS_RUN_AS_APIKEY"

DATAOS_SECRET_DIR = "DATAOS_SECRET_DIR"

DEPOT_SERVICE_URL = "DEPOT_SERVICE_URL"

CONFIG_FILE_PATH = "CONFIG_FILE_PATH" # set this in stack
CONFIG_FILE_PATH_DEFAULT = "stack/sample-input.yaml"

